### PR TITLE
You forgor a thing in playstate

### PR DESCRIPTION
**Pull request by jmxamongusmodder**
when you add new achievements add them to the playstate thing like i did here
also is firemedia a week or a song
must be a week to work thats how it works
also linux no compile if you want more commits out of me ill do so.
:skull: :skull: :skull: :skull: :skull: :skull:

### CODE REVIEW

**Comment by MemeHoovy** [comment]
you didn't have to remove the song specific scripts comment btw

**Comment by MemeHoovy** [comment]
but whatever

**Comment by myffs** [comment]
> when you add new achievements add them to the playstate thing like i did here also is firemedia a week or a song must be a week to work thats how it works also linux no compile if you want more commits out of me ill do so. 💀 💀 💀 💀 💀 💀

who tf added you

**Comment by MemeHoovy** [comment]
he just contributed via a PR, he can't contribute to the main repo

**Pull request merged**
